#from neural_nlp.models.gpt_neox_model.modeling_gpt_neox import GPTNeoXForCausalLM, GPTNeoXModel
#from neural_nlp.models.gpt_neox_model.configuration_gpt_neox import GPTNeoXConfig
from transformers import GPT2Tokenizer
#from transformers import GPT2BPETokenizer
from neural_nlp.models.gpt_neox_model.modeling_gpt_neox import  GPTNeoXModel, GPTNeoXForCausalLM
from neural_nlp.models.gpt_neox_model.configuration_gpt_neox import GPTNeoXConfig
from neural_nlp.models.gpt_neox_model.configuration_gpt_neox import GPTNeoXPosLearnedConfig
from neural_nlp.models.gpt_neox_model.modeling_gpt_neox_learned import GPTNeoXPosLearnedForCausalLM,GPTNeoXPosLearnedModel